### ISSUE TITLE
Crash if "Detecting Cards..." takes too long

### ISSUE THREAD

**Issue by n4ru** [corlettb/Arena-Helper#1]
Like the title states, if detecting cards takes too long (more than ~4-5 seconds on my end), the plugin crashes and I have to Disable/Re-enable it to reopen it from the plugins menu. This is consistent, and I've had to re-open the plugin five times on a certain selection. 

Might have something to do with the detection taking too long and crashing from your code expecting a value too soon? I haven't skimmed your code yet and I don't know C# at all so this is a wild guess :P

My computer is pretty dated and Hearthstone is slow even on low, so it may be hard to recreate the issue with a fast computer.

**Comment by corlettb** [comment]
I believe if the plugin blocks for more than 5 seconds then HDT with disable the plugin automatically. It could be the the http get is taking more than 5 seconds from where you are. Hows your internet?

**Comment by n4ru** [comment]
Latency wise it's fine (21ms via PingTest with 7ms Jitter). I don't think that's the issue unless something would cause it to take that long during the detection.

**Comment by corlettb** [comment]
Thought you might be on some packet loss ridden 3g connection or something... there is me hoping... Just in the middle of an arena atm... which means I can't really test anything... but I'll take a look once I'm done.

**Comment by corlettb** [comment]
So is it happening consistent on the same pick of cards?

**Comment by n4ru** [comment]
Yes, although it eventually does detect and work properly.

**Comment by corlettb** [comment]
Does it seem to get worse the further you get into the deck build?

**Comment by n4ru** [comment]
Yep. Is it some sort of memory or overflow issue?

**Comment by corlettb** [comment]
So it might be the translation of the codes between how HearhArena identify a card and how Arena helper identifies them.

At the moment it just searches through a large list to find them each time. At pick one it only needs to do this 3 times... but by pick 30 it will need to do it 29 (all current picks) + 3 times (for the options).

I can probably populate a hash on load with this information so its much quicker.

If your CPU is pretty loaded at this time by the game and this going on it could be this.

**Comment by corlettb** [comment]
Wanna give this one a go:

https://mega.co.nz/#!ApdQTT5L!TkFUMEGIYukDH4dYoJ02Bjo1sT8H8XgwbnesHLoPn6M

**Comment by n4ru** [comment]
That resolved the issue.

**Comment by corlettb** [comment]
Winner
